"""Adjust the columns of Recipe

Revision ID: 9f397b4e7485
Revises: 2810f8dbb6b2
Create Date: 2023-06-08 18:38:02.624265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f397b4e7485'
down_revision = '2810f8dbb6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('contents', sa.Text(), nullable=False))
        batch_op.alter_column('ingredients',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('steps')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('steps', mysql.TEXT(), nullable=True))
        batch_op.alter_column('ingredients',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('contents')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
