"""Adjust the columns of Recipe

Revision ID: a83557ae1035
Revises: 2810f8dbb6b2
Create Date: 2023-06-07 16:23:49.812570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a83557ae1035'
down_revision = '2810f8dbb6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=False))
        batch_op.alter_column('ingredients',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('steps',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('steps',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('ingredients',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
