"""Add token to Recipe and make the entire structure more strict

Revision ID: dae19ea06c81
Revises: 9f397b4e7485
Create Date: 2023-06-11 05:54:18.239905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae19ea06c81'
down_revision = '9f397b4e7485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id', 'recipe_id'])

    with op.batch_alter_table('followerships', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['follower_id', 'followed_id'])

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint(None, ['token'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['account'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token')

    with op.batch_alter_table('followerships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
